name=input("enter your name:")
sem=int(input("enter your semester:"))
city=input("enter your city name:")
pincode=int(input("enter a pincode of your city:"))
print("\n\n\n")
print("student name:",name)
print("semester:",sem)
print("city:",city)
print("pincode:",pincode)
